name: M1 Mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-mac:
    runs-on: macos-14
    steps:
    - name: install clang
      shell: bash
      run: brew install llvm@17
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: images
        key: key
    - id: cached
      uses: andstor/file-existence-action@v3
      with:
        files: images
    - name: get benchmark suite
      if: steps.cached.outputs.files_exists == 'false'
      shell: bash
      run: curl https://qoiformat.org/benchmark/qoi_benchmark_suite.tar | tar x
    - name: build
      shell: bash
      run: CXX=$(brew --prefix llvm@17)/bin/clang++ make -j
    - name: run
      shell: bash
      run: bin/qoibench 1 images --noreference --nowarmup
    - name: test
      shell: bash
      run: bin/test
