name: Windows(msys2)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ucrt64
        install: >-
          git
          curl
          mingw-w64-ucrt-x86_64-make
          mingw-w64-ucrt-x86_64-clang
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: images
        key: key
    - id: cached
      uses: andstor/file-existence-action@v3
      with:
        files: images
    - name: get benchmark suite
      if: steps.cached.outputs.files_exists == 'false'
      shell: bash
      run: curl https://qoiformat.org/benchmark/qoi_benchmark_suite.tar | tar x
    - name: build
      shell: msys2 {0}
      run: CXX=clang++ mingw32-make -j
    - name: run
      shell: msys2 {0}
      run: bin/qoibench 1 images --noreference --nowarmup
    - name: test
      shell: msys2 {0}
      run: bin/test
